# **HYPOTHESIS TESTING ASSIGNMENT**

# Q-1

In [1]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats

In [2]:
cutlet = pd.read_csv('Cutlets.csv')
cutlet

    Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [3]:
cutlet.describe()

          Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [4]:
unit_a = pd.Series(cutlet.iloc[:,0])
unit_a

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unit_b = pd.Series(cutlet.iloc[:,1])
unit_b

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

# As the manager wants to compare between 2 samples, it is a 2-sample t test.

In [6]:
t_stats,p_value = stats.ttest_ind(unit_a,unit_b)
t_stats,p_value

(0.7228688704678063, 0.4722394724599501)

In [7]:
print('p_value for the 2 sample test is : ', p_value,)

p_value for the 2 sample test is :  0.4722394724599501

#The p-value < 0.05 so we can accept the Altenate Hypothesis

# Q-2

In [8]:
lab = pd.read_csv('LabTAT.csv')
lab.head(10)

   Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60
5        179.45        197.00        181.51        161.12
6        191.37        166.36        214.21        154.02
7        166.81        169.60        183.43        163.25
8        158.81        175.36        191.60        152.79
9        165.88        198.68        208.43        161.98

In [9]:
lab1 = pd.Series(lab.iloc[:,0])
lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [10]:
lab2 = pd.Series(lab.iloc[:,1])
lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [11]:
lab3 = pd.Series(lab.iloc[:,2])
lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [12]:
lab4 = pd.Series(lab.iloc[:,3])
lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [13]:
lab.describe()

       Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [14]:
f_stats, p_value = stats.f_oneway(lab.iloc[:,0],lab.iloc[:,1],lab.iloc[:,2],lab.iloc[:,3])
p_value

2.1156708949992414e-57

In [15]:
print('P-Value is greater than 0.05 , so accept the NULL HYPOTHESIS')

P-Value is greater than 0.05 , so accept the NULL HYPOTHESIS

#Here the p_value > 0.05 so accept the NULL HYPOTHESIS.

# Q-3

In [16]:
df2 = pd.read_csv('BuyerRatio.csv')
df2

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64
 2   West             2 non-null      int64
 3   North            2 non-null      int64
 4   South            2 non-null      int64
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes

In [18]:
df2.describe()

             East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [19]:
count=np.array([[50, 142, 131, 70], [435, 1523, 1356, 750]])
count

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [20]:
ttest_value = stats.chi2_contingency(count)
ttest_value

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [21]:
print("ACCEPT H0")

ACCEPT H0

#Q- 4

In [22]:
from scipy import stats
from scipy.stats import chi2
from scipy.stats import chi2_contingency

In [26]:
df5 = pd.read_csv('costomerOrderForm.csv')
df5

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [27]:
df5.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [29]:
df5['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [30]:
df5['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [31]:
df5['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [32]:
df5['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [33]:
values=np.array([[271,267,269,280],[29,33,31,20]])
values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [34]:
chi_2_value= chi2_contingency(values)

In [38]:
chi_2_value

Chi2ContingencyResult(statistic=3.858960685820355, pvalue=0.2771020991233135, dof=3, expected_freq=array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))

In [39]:
print("p_value = 0.2771020991233135")

p_value = 0.2771020991233135

In [40]:
#So p-value >0.05 so accept NULL HYPOTHESIS
print("ACCEPT NULL HYPOTHESIS")

ACCEPT NULL HYPOTHESIS